### ISSUE TITLE
Infected files reported. What next?

### ISSUE THREAD

**Issue by cyberfunk** [mikestowe/Malicious-Code-Scanner#9]
Hello and thanks for this wonderful script. I ran it on a folder and it reported back that two separate .js files were infected. I opened each of the files with a text editor but am not sure what to look for in the code. I searched for "64" and nothing came up in either file. In the past I have discovered malicious code disguised inside a fake png file that linked to casino and other spam sites which is why I'm using your script this time around. Any tips on how to scan or screen these .js files is much appreciated.

**Comment by sandrosdj** [comment]
This code is looking for these in files: eval, base64, $_/$$,(letters, numbers, {[]})
I'm not sure if my understanding of the regex is correct here, but it must be something similar.

You'll get a list of "infected" files. Then you can decide if you remove the malicious code from it, re-download it from where you got it or rewrite it. It is possible that the detected file has no malicious code inside (known false alarm for WordPress icss.class.php, some Drupal files).

This project is /mainly/ for malicious php code scanning, not js. If any of your non-php files contain php code, than that's a problem, but those can't run unless you feed it to eval(). To make sure your js file is clean, you can use various online tools such as virustotal, virscan.

**Comment by cyberfunk** [comment]
Thanks @sandrosdj!
